apiVersion: v1
kind: Service
metadata:
  name: team-service
spec:
  type: NodePort
  selector:
    app: team-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
